---
- hosts: servers
  become: yes
  vars:
    ansible_user: "root"
  tasks:
  - name: Login to Rancher
    shell: |
      spawn rancher login https://rh1 --token token-m8sc4:gk7l9l46pvlqfzhpvrjs7c57b57z79jdxbplvzjdzxrdd4txzdsb69 
      expect "Do you want to continue connecting (yes/no)?"
      send y\n;
      exit 0
    args:
      executable: /usr/bin/expect
  - name: Choose the deployment
    shell: |
      spawn rancher context switch
      expect "Select a Project:"
      send 3\n;
      exit 0
    args:
      executable: /usr/bin/expect
  - name: Update the deployment
    script:
      cmd: /usr/bin/update_cicd.sh