---
- hosts: servers
  become: yes
  vars:
    ansible_user: "root"
  tasks:
  - name: Choose the deployment
    shell: |
      spawn rancher context switch
      expect "Select a Project:"
      send 3\n;
      exit 0
    args:
      executable: /usr/bin/expect
  - name: Update the deployment
    shell:
      cmd: rancher kubectl image deployment/cicd cicd=kuzko/cicd:latest
      